### ISSUE TITLE
Critical vulnerability in log4net

### ISSUE THREAD

**Issue by thijs1970** [mortenbra/thoth-gateway#8]
A critical vulnerability was discovered in file log4net. The CVE Dictionary Entry for this issue is CVE-2018-1285. All log4net versions before 2.0.10 are effected. The thoth-gateway contains log4net version 1.2.20.0. Will there be a new version of thoth-gateway with the latest log4net?

**Comment by mortenbra** [comment]
Shouldn't be a problem using the latest log4net version in future releases of the Thoth Gateway.

However, note that according to the description of the vulnerability, "_Apache log4net versions before 2.0.10 do not disable XML external entities when parsing log4net configuration files. This allows for XXE-based attacks in applications that accept attacker-controlled log4net configuration files._" This means an attacker must already have compromised your web server in order to use this vulnerability, in which case you have bigger problems to worry about...

**Comment by thijs1970** [comment]
Thanks for your reply. I will manually replace the log4net file with the newest version on the server and make my network administrator happy again.

**Comment by mortenbra** [comment]
Note to self: log4net release notes here: http://logging.apache.org/log4net/release/release-notes.html

**Comment by mortenbra** [comment]
Fixed in upcoming v1.4.5 release, which includes log4net 20.0.12.0.

**Comment by thijs1970** [comment]
Thank you very much
